version: '3'  # version of compose format 

services:
  app:
    build: ./  # path is relative to docker-compose.yml localtion
    volumes:
      - ./:/usr/src/app # mount point
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=local_db
      - POSTGRES_PASSWORD=locpass
      - DB_HOST = db

    depends_on:
      - db

  db:
    image: postgres:14.6-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - 'postgresql-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=local_db
      - POSTGRES_PASSWORD=locpass
      - POSTGRES_HOST_AUTH_METHOD=trust
      - DB_HOST = db
    volumes:
      - pgdata:/var/lib/postgresql/data
      
volumes:
  pgdata: {}